name: Update View

on:
  issues: 
    types: 
      - labeled

permissions:
  contents: read

jobs:
  build:
    if: github.event.label.name == 'help-wanted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test 
      run: |
        echo "Its Working"
